--liquibase formatted sql
--changeset Stanislaw|Przemyslaw:1 labels:init,tables

CREATE TABLE website_user
(
    user_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(50) UNIQUE  NOT NULL,
    email               VARCHAR(100) UNIQUE NOT NULL,
    password            VARCHAR(255)        NOT NULL,
    full_name           VARCHAR(100),
    bio                 TEXT,
    profile_picture_url VARCHAR(255),
    join_date           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE user_role
(
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES website_user (user_id),
    role_id      BIGINT NOT NULL REFERENCES role (role_id)
);

CREATE TABLE post
(
    post_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES website_user (user_id),
    description TEXT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP,
    deleted_at  TIMESTAMP
);

CREATE TABLE comment
(
    comment_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL REFERENCES website_user (user_id),
    post_id           BIGINT NOT NULL REFERENCES post (post_id),
    parent_comment_id BIGINT REFERENCES comment (comment_id),
    text              TEXT   NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP
);

CREATE TABLE post_like
(
    post_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES website_user (user_id),
    post_id      BIGINT NOT NULL REFERENCES post (post_id)
);

CREATE TABLE comment_like
(
    comment_like_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES website_user (user_id),
    comment_id      BIGINT NOT NULL REFERENCES comment (comment_id)
);

CREATE TABLE follow
(
    follow_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT NOT NULL REFERENCES website_user (user_id),
    followed_id BIGINT NOT NULL REFERENCES website_user (user_id),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notification
(
    notification_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL REFERENCES website_user (user_id), -- The one who gets notified
    triggered_by_id   BIGINT      NOT NULL REFERENCES website_user (user_id), -- The one who triggered the notification
    notification_type VARCHAR(50) NOT NULL,                                   -- Can be 'like', 'comment', 'follow'
    post_id           BIGINT REFERENCES post (post_id),                       -- Nullable if not related to a post
    comment_id        BIGINT REFERENCES comment (comment_id),                 -- Add short_id later
    is_read           boolean     NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP            DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE message
(
    message_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id    BIGINT  NOT NULL REFERENCES website_user (user_id),
    receiver_id  BIGINT  NOT NULL REFERENCES website_user (user_id),
    message_text TEXT    NOT NULL,
    is_read      boolean NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP
);

CREATE TABLE medium
(
    medium_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT       NOT NULL REFERENCES post (post_id),
    medium_url  VARCHAR(255) NOT NULL,
    medium_type VARCHAR(50)  NOT NULL -- Can be 'image' or 'video'
);

CREATE TABLE hashtag
(
    hashtag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hashtag    VARCHAR(100) NOT NULL,
    post_id    BIGINT       NOT NULL REFERENCES post (post_id)
);


--changeset Stanislaw:2 labels:init,fix
ALTER TABLE website_user
    ADD COLUMN deleted_at TIMESTAMP;

